version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./app/database:/app/database
    environment:
      FLASK_ENV: development
